In [2]:
import os
import pandas as pd
import numpy as np
import scipy.sparse as sp
import torch

In [3]:
data_dir = '/home/ashvinee/Documents/Ferrato/Data/all_ings/'

In [4]:
ingg = pd.read_csv('/home/ashvinee/Documents/Ferrato/Data/all_ingredients_name.csv')
col = list(ingg.In)
cols = ['Dish Type','Title']+col

In [5]:
citations = pd.read_csv(
    "/home/ashvinee/Documents/Ferrato/Data/breakfast_ingredients_835_final6.csv",
    sep=",",
    header=None,
    names=cols,
)

/home/ashvinee/.local/share/virtualenvs/Ferrato-aimIbf9P/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,2

In [6]:
citations

Dish Type  Title  salt  pepper  butter  garlic  sugar  \
NaN   Total Ing index  Dish Type  Title  salt  pepper  butter  garlic  sugar   
1.0   22        0.0            0    283     1       0       0       0      0   
2.0   64        1.0            0    101     1       0       0       0      0   
3.0   58        2.0            0    463     1       1       0       1      0   
4.0   22        3.0            0    283     1       0       0       0      0   
...                          ...    ...   ...     ...     ...     ...    ...   
850.0 13        849.0          1    468     0       0       1       0      0   
851.0 43        850.0          1    165     1       1       1       1      0   
852.0 47        851.0          1    165     1       0       1       0      1   
853.0 32        852.0          1    128     1       0       0       1      0   
854.0 27        853.0          1    128     1       0       1       0      1   

                       flour  onion  olive oil  ...  cooked meatballs  \
NaN   Total Ing index  flour  onion  olive oil  ...  cooked meatballs   
1.0   22        0.0        0      0          0  ...                 0   
2.0   64        1.0        0      1          0  ...                 0   
3.0   58        2.0        0      0          0  ...                 0   
4.0   22        3.0        0      0          0  ...                 0   
...                      ...    ...        ...  ...               ...   
850.0 13        849.0      1      0          0  ...                 0   
851.0 43        850.0      0      1          0  ...                 0   
852.0 47        851.0      1      0          0  ...                 0   
853.0 32        852.0      0      0          0  ...                 0   
854.0 27        853.0      1      0          0  ...                 0   

                       beef sausage  mulberries  fine egg noodles  linguica  \
NaN   Total Ing index  beef sausage  mulberries  fine egg noodles  linguica   
1.0   22        0.0               0           0                 0         0   
2.0   64        1.0               0           0                 0         0   
3.0   58        2.0               0           0                 0         0   
4.0   22        3.0               0           0                 0         0   
...                             ...         ...               ...       ...   
850.0 13        849.0             0           0                 0         0   
851.0 43        850.0             0           0                 0         0   
852.0 47        851.0             0           0                 0         0   
853.0 32        852.0             0           0                 0         0   
854.0 27        853.0             0           0                 0         0   

                       poblano chilies  crystal hot sauce  watercress leaves  \
NaN   Total Ing index  poblano chilies  crystal hot sauce  watercress leaves   
1.0   22        0.0                  0                  0                  0   
2.0   64        1.0                  0                  0                  0   
3.0   58        2.0                  0                  0                  0   
4.0   22        3.0                  0                  0                  0   
...                                ...                ...                ...   
850.0 13        849.0                0                  0                  0   
851.0 43        850.0                0                  0                  0   
852.0 47        851.0                0                  0                  0   
853.0 32        852.0                0                  0                  0   
854.0 27        853.0                0                  0                  0   

                       emerils essence  corn flakes cereal  
NaN   Total Ing index  emerils essence  corn flakes cereal  
1.0   22        0.0                  0                   0  
2.0   64        1.0                  0                   0  
3.0   58        2.0            

In [7]:
citations = citations.reset_index()

In [8]:
citations = citations.drop(citations.index[0])

In [9]:
citations = citations.drop('level_0', axis=1)

In [10]:
citations = citations.drop('level_1', axis=1)

In [11]:
citations = citations.drop('level_2', axis=1)

In [12]:
#citations = citations.drop('Dish Type', axis=1)

In [13]:
title = citations.Title.values
citations = citations.drop('Title', axis=1)

In [14]:
# citations.index = citations.index.astype('int')

In [15]:
cc = citations.to_numpy().astype(int)

In [16]:
cc

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]])

In [17]:
# sa = [int(i) for i in cc[0]]
# ar = np.array([sa])

# for sa in range(1,cc.shape[0]):
#     ll = [int(i) for i in cc[sa]]
#     ar = np.append(ar, [ll], axis=0)
    


In [18]:
cc.shape

(854, 3501)

In [19]:
features = sp.csr_matrix(cc, dtype=np.float32)

In [20]:
features

<854x3501 sparse matrix of type '<class 'numpy.float32'>'
	with 21743 stored elements in Compressed Sparse Row format>

In [21]:
def encode_onehot(labels):
    classes = set(labels)
    classes_dict = {c: np.identity(len(classes))[i, :] for i, c in
                    enumerate(classes)}
    labels_onehot = np.array(list(map(classes_dict.get, labels)),
                             dtype=np.int32)
    return labels_onehot


In [22]:
labels = encode_onehot(cc[:,0])

In [23]:
labels

array([[1, 0],
       [1, 0],
       [1, 0],
       ...,
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int32)

In [24]:
title = title.astype(int)

In [25]:
# build graph
idx = np.array(title, dtype=np.int32)
idx_map = {j: i for i, j in enumerate(idx)}

In [26]:
#edges_unordered = np.genfromtxt("{}{}.cites".format(path, dataset), dtype=np.int32)
edges_unordered = pd.read_csv(
    "/home/ashvinee/Documents/Ferrato/Data/similar_ingredients.csv",
    sep=",",
    header=None,
    names=['FTitle', 'STitle', 'Sting'],
)

In [27]:
edges_unordered

FTitle  STitle  Sting
NaN    FTitle  STitle  Sting
1.0       283     239     22
2.0       283     310     22
4.0       283      66     22
5.0       283     251     22
...       ...     ...    ...
253.0     292     193     17
254.0     292     190     17
255.0     292      37     17
256.0     292      75     17
257.0     292     435     17

[178 rows x 3 columns]

In [28]:
edges_unordered = edges_unordered.reset_index()
edges_unordered = edges_unordered.drop('index', axis=1)
edges_unordered = edges_unordered.drop(index=0, axis=0)

In [29]:
edges_unordered = edges_unordered.to_numpy().astype(int)

In [30]:
edges = np.array(list(map(idx_map.get, edges_unordered.flatten())),
                     dtype=np.int32).reshape(edges_unordered.shape)

In [31]:
adj = sp.coo_matrix((np.ones(edges.shape[0]), (edges[:, 0], edges[:, 1])),
                        shape=(labels.shape[0], labels.shape[0]),
                        dtype=np.float32)

In [32]:
# build symmetric adjacency matrix
adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)

In [33]:
def normalize(mx):
    """Row-normalize sparse matrix"""
    rowsum = np.array(mx.sum(1))
    r_inv = np.power(rowsum, -1).flatten()
    r_inv[np.isinf(r_inv)] = 0.
    r_mat_inv = sp.diags(r_inv)
    mx = r_mat_inv.dot(mx)
    return mx

In [34]:
# features = normalize(features)
# adj = normalize(adj + sp.eye(adj.shape[0]))

In [35]:
features

<854x3501 sparse matrix of type '<class 'numpy.float32'>'
	with 21743 stored elements in Compressed Sparse Row format>

In [36]:
idx_train = range(140)
idx_val = range(200, 500)
idx_test = range(500, 1500)

In [37]:
def sparse_mx_to_torch_sparse_tensor(sparse_mx):
    """Convert a scipy sparse matrix to a torch sparse tensor."""
    sparse_mx = sparse_mx.tocoo().astype(np.float32)
    indices = torch.from_numpy(
        np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
    values = torch.from_numpy(sparse_mx.data)
    shape = torch.Size(sparse_mx.shape)
    return torch.sparse.FloatTensor(indices, values, shape)

In [38]:
features

<854x3501 sparse matrix of type '<class 'numpy.float32'>'
	with 21743 stored elements in Compressed Sparse Row format>

In [39]:
features = torch.FloatTensor(np.array(features.todense()))
labels = torch.LongTensor(np.where(labels)[1])

In [40]:
# features = torch.FloatTensor(np.array(features.todense()))
# adj = sparse_mx_to_torch_sparse_tensor(adj)

In [41]:
adj = sparse_mx_to_torch_sparse_tensor(adj)

In [42]:
idx_train = torch.LongTensor(idx_train)
idx_val = torch.LongTensor(idx_val)
idx_test = torch.LongTensor(idx_test)

In [43]:
#return adj, features, labels, idx_train, idx_val, idx_test

In [44]:
adj[0]

tensor(indices=tensor([], size=(1, 0)),
       values=tensor([], size=(0,)),
       size=(854,), nnz=0, layout=torch.sparse_coo)

In [45]:
# tensor(indices=tensor([[   0,    8,   14,  ..., 1389, 2344, 2707],
#                        [   0,    0,    0,  ..., 2707, 2707, 2707]]),
#        values=tensor([0.1667, 0.1667, 0.0500,  ..., 0.2000, 0.5000, 0.2500]),
#        size=(2708, 2708), nnz=13264, layout=torch.sparse_coo)

In [46]:
features

tensor([[0., 1., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 0., 0., 0.],
        ...,
        [1., 1., 0.,  ..., 0., 0., 0.],
        [1., 1., 0.,  ..., 0., 0., 0.],
        [1., 1., 0.,  ..., 0., 0., 0.]])

In [47]:
# tensor([[0., 0., 0.,  ..., 0., 0., 0.],
#         [0., 0., 0.,  ..., 0., 0., 0.],
#         [0., 0., 0.,  ..., 0., 0., 0.],
#         ...,
#         [0., 0., 0.,  ..., 0., 0., 0.],
#         [0., 0., 0.,  ..., 0., 0., 0.],
#         [0., 0., 0.,  ..., 0., 0., 0.]])

In [48]:
labels

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [49]:
# tensor([5, 3, 4,  ..., 0, 6, 5])

In [50]:
idx_train

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139])

In [51]:
# tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
#          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
#          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
#          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
#          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
#          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
#          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
#          98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
#         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
#         126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139])

In [52]:
idx_val

tensor([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
        214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
        228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
        242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
        256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269,
        270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283,
        284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297,
        298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
        312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
        326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339,
        340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353,
        354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367,
        368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 3

In [53]:
# tensor([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
#         214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
#         228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
#         242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
#         256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269,
#         270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283,
#         284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297,
#         298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
#         312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
#         326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339,
#         340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353,
#         354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367,
#         368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381,
#         382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395,
#         396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409,
#         410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423,
#         424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437,
#         438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
#         452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465,
#         466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479,
#         480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
#         494, 495, 496, 497, 498, 499])

In [54]:
idx_test

tensor([ 500,  501,  502,  503,  504,  505,  506,  507,  508,  509,  510,  511,
         512,  513,  514,  515,  516,  517,  518,  519,  520,  521,  522,  523,
         524,  525,  526,  527,  528,  529,  530,  531,  532,  533,  534,  535,
         536,  537,  538,  539,  540,  541,  542,  543,  544,  545,  546,  547,
         548,  549,  550,  551,  552,  553,  554,  555,  556,  557,  558,  559,
         560,  561,  562,  563,  564,  565,  566,  567,  568,  569,  570,  571,
         572,  573,  574,  575,  576,  577,  578,  579,  580,  581,  582,  583,
         584,  585,  586,  587,  588,  589,  590,  591,  592,  593,  594,  595,
         596,  597,  598,  599,  600,  601,  602,  603,  604,  605,  606,  607,
         608,  609,  610,  611,  612,  613,  614,  615,  616,  617,  618,  619,
         620,  621,  622,  623,  624,  625,  626,  627,  628,  629,  630,  631,
         632,  633,  634,  635,  636,  637,  638,  639,  640,  641,  642,  643,
         644,  645,  646,  647,  648,  6

In [55]:
# tensor([ 500,  501,  502,  503,  504,  505,  506,  507,  508,  509,  510,  511,
#          512,  513,  514,  515,  516,  517,  518,  519,  520,  521,  522,  523,
#          524,  525,  526,  527,  528,  529,  530,  531,  532,  533,  534,  535,
#          536,  537,  538,  539,  540,  541,  542,  543,  544,  545,  546,  547,
#          548,  549,  550,  551,  552,  553,  554,  555,  556,  557,  558,  559,
#          560,  561,  562,  563,  564,  565,  566,  567,  568,  569,  570,  571,
#          572,  573,  574,  575,  576,  577,  578,  579,  580,  581,  582,  583,
#          584,  585,  586,  587,  588,  589,  590,  591,  592,  593,  594,  595,
#          596,  597,  598,  599,  600,  601,  602,  603,  604,  605,  606,  607,
#          608,  609,  610,  611,  612,  613,  614,  615,  616,  617,  618,  619,
#          620,  621,  622,  623,  624,  625,  626,  627,  628,  629,  630,  631,
#          632,  633,  634,  635,  636,  637,  638,  639,  640,  641,  642,  643,
#          644,  645,  646,  647,  648,  649,  650,  651,  652,  653,  654,  655,
#          656,  657,  658,  659,  660,  661,  662,  663,  664,  665,  666,  667,
#          668,  669,  670,  671,  672,  673,  674,  675,  676,  677,  678,  679,
#          680,  681,  682,  683,  684,  685,  686,  687,  688,  689,  690,  691,
#          692,  693,  694,  695,  696,  697,  698,  699,  700,  701,  702,  703,
#          704,  705,  706,  707,  708,  709,  710,  711,  712,  713,  714,  715,
#          716,  717,  718,  719,  720,  721,  722,  723,  724,  725,  726,  727,
#          728,  729,  730,  731,  732,  733,  734,  735,  736,  737,  738,  739,
#          740,  741,  742,  743,  744,  745,  746,  747,  748,  749,  750,  751,
#          752,  753,  754,  755,  756,  757,  758,  759,  760,  761,  762,  763,
#          764,  765,  766,  767,  768,  769,  770,  771,  772,  773,  774,  775,
#          776,  777,  778,  779,  780,  781,  782,  783,  784,  785,  786,  787,
#          788,  789,  790,  791,  792,  793,  794,  795,  796,  797,  798,  799,
#          800,  801,  802,  803,  804,  805,  806,  807,  808,  809,  810,  811,
#          812,  813,  814,  815,  816,  817,  818,  819,  820,  821,  822,  823,
#          824,  825,  826,  827,  828,  829,  830,  831,  832,  833,  834,  835,
#          836,  837,  838,  839,  840,  841,  842,  843,  844,  845,  846,  847,
#          848,  849,  850,  851,  852,  853,  854,  855,  856,  857,  858,  859,
#          860,  861,  862,  863,  864,  865,  866,  867,  868,  869,  870,  871,
#          872,  873,  874,  875,  876,  877,  878,  879,  880,  881,  882,  883,
#          884,  885,  886,  887,  888,  889,  890,  891,  892,  893,  894,  895,
#          896,  897,  898,  899,  900,  901,  902,  903,  904,  905,  906,  907,
#          908,  909,  910,  911,  912,  913,  914,  915,  916,  917,  918,  919,
#          920,  921,  922,  923,  924,  925,  926,  927,  928,  929,  930,  931,
#          932,  933,  934,  935,  936,  937,  938,  939,  940,  941,  942,  943,
#          944,  945,  946,  947,  948,  949,  950,  951,  952,  953,  954,  955,
#          956,  957,  958,  959,  960,  961,  962,  963,  964,  965,  966,  967,
#          968,  969,  970,  971,  972,  973,  974,  975,  976,  977,  978,  979,
#          980,  981,  982,  983,  984,  985,  986,  987,  988,  989,  990,  991,
#          992,  993,  994,  995,  996,  997,  998,  999, 1000, 1001, 1002, 1003,
#         1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015,
#         1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027,
#         1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039,
#         1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051,
#         1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063,
#         1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075,
#         1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087,
#         1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099,
#         1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111,
#         1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123,
#         1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135,
#         1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147,
#         1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159,
#         1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171,
#         1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183,
#         1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195,
#         1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207,
#         1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219,
#         1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231,
#         1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243,
#         1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255,
#         1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267,
#         1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279,
#         1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291,
#         1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303,
#         1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315,
#         1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327,
#         1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339,
#         1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351,
#         1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363,
#         1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375,
#         1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387,
#         1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399,
#         1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411,
#         1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423,
#         1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435,
#         1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447,
#         1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459,
#         1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471,
#         1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483,
#         1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495,
#         1496, 1497, 1498, 1499])

In [56]:
len(idx_test)

1000

In [57]:
import time
import argparse
import numpy as np
import copy
import torch
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler
#from utils import load_data, accuracy
#from models import GCN
#from onnix_food import export_onnix, ColaPredictor
#import wandb
import os
#import hydra
#from omegaconf import OmegaConf

import torch.nn as nn
import torch.nn.functional as F
#from layers import GraphConvolution
import torch
from torch.nn import Linear
from torch_geometric.nn import GCNConv

import math

import torch

from torch.nn.parameter import Parameter
from torch.nn.modules.module import Module

In [58]:
np.random.seed(42)
torch.manual_seed(42)
#cfg.training.cuda = not cfg.processing.no_cuda and torch.cuda.is_available()
if False:
    torch.cuda.manual_seed(cfg.training.seed)

In [59]:
class GraphConvolution(Module):
    """
    Simple GCN layer, similar to https://arxiv.org/abs/1609.02907
    """

    def __init__(self, in_features, out_features, bias=True):
        super(GraphConvolution, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = Parameter(torch.FloatTensor(in_features, out_features))
        if bias:
            self.bias = Parameter(torch.FloatTensor(out_features))
        else:
            self.register_parameter('bias', None)
        self.reset_parameters()

    def reset_parameters(self):
        stdv = 1. / math.sqrt(self.weight.size(1))
        self.weight.data.uniform_(-stdv, stdv)
        if self.bias is not None:
            self.bias.data.uniform_(-stdv, stdv)

    def forward(self, input, adj):
        support = torch.mm(input, self.weight)
        output = torch.spmm(adj, support)
        if self.bias is not None:
            return output + self.bias
        else:
            return output

    def __repr__(self):
        return self.__class__.__name__ + ' (' \
               + str(self.in_features) + ' -> ' \
               + str(self.out_features) + ')'

In [60]:
class GCN(nn.Module):
    def __init__(self, nfeat, nhid, nclass, dropout):
        super(GCN, self).__init__()

        self.gc1 = GraphConvolution(nfeat, nhid)
        self.gc2 = GraphConvolution(nhid, nclass)
        self.dropout = dropout

    def forward(self, x, adj):
        x = F.relu(self.gc1(x, adj))
        x = F.dropout(x, self.dropout, training=self.training)
        x = self.gc2(x, adj)
        return F.log_softmax(x, dim=1)


In [61]:
# Model and optimizer
model = GCN(nfeat=features.shape[1],
            nhid=16,
            nclass=labels.max().item() + 1,
            dropout=0.5)

In [62]:
model

GCN(
  (gc1): GraphConvolution (3501 -> 16)
  (gc2): GraphConvolution (16 -> 2)
)

In [63]:
!pip install torchsummary 

In [64]:
adj.shape

torch.Size([854, 854])

In [65]:
features.shape

torch.Size([854, 3501])

In [66]:
# from torchsummary import summary

# summary(model, input_size=(3501,16,3501), input_size=(3501,16,3501))

In [67]:
optimizer = optim.Adam(model.parameters(),lr=0.1, weight_decay=5e-4)

In [68]:
exp_lr_scheduler = lr_scheduler.StepLR(optimizer, step_size=7, gamma=0.1)

In [69]:
# Train model
def train(model, optimizer, scheduler, adj, features, labels, idx_train, idx_val):
    t_total = time.time()
    best_model_wts = copy.deepcopy(model.state_dict())
    best_acc = 0.0
    for epoch in range(20):
        #train(epoch)
        t = time.time()
        model.train()
        optimizer.zero_grad()
        output = model(features, adj)
        loss_train = F.nll_loss(output[idx_train], labels[idx_train])
        acc_train = accuracy(output[idx_train], labels[idx_train])
        loss_train.backward()
        optimizer.step()
        #scheduler.step()
        if not False:
            # Evaluate validation set performance separately,
            # deactivates dropout during validation run.
            model.eval()
            output = model(features, adj)

        loss_val = F.nll_loss(output[idx_val], labels[idx_val])
        acc_val = accuracy(output[idx_val], labels[idx_val])

        if acc_val > best_acc:
            best_acc = acc_val
            best_model_wts = copy.deepcopy(model.state_dict())
        
        print('Epoch: {:04d}'.format(epoch + 1),
              'loss_train: {:.4f}'.format(loss_train.item()),
              'acc_train: {:.4f}'.format(acc_train.item()),
              'loss_val: {:.4f}'.format(loss_val.item()),
              'acc_val: {:.4f}'.format(acc_val.item()),
              'time: {:.4f}s'.format(time.time() - t))
        
        time_elapsed = time.time() - t_total
        print('Training complete in {:.0f}m {:.0f}s'.format(
            time_elapsed // 60, time_elapsed % 60))
        print('Best val Acc: {:4f}'.format(best_acc))
    
    # load best model weights
    model.load_state_dict(best_model_wts)

    return model, loss_train


In [70]:
def accuracy(output, labels):
    preds = output.max(1)[1].type_as(labels)
    correct = preds.eq(labels).double()
    correct = correct.sum()
    return correct / len(labels)

In [71]:
model_ft, loss = train(model, optimizer, exp_lr_scheduler, adj, features, labels, idx_train, idx_val)

Epoch: 0001 loss_train: 5.1037 acc_train: 0.6643 loss_val: 10.5347 acc_val: 0.0000 time: 0.0448s
Training complete in 0m 0s
Best val Acc: 0.000000
Epoch: 0002 loss_train: 0.4400 acc_train: 0.9714 loss_val: 17.5512 acc_val: 0.0000 time: 0.0099s
Training complete in 0m 0s
Best val Acc: 0.000000
Epoch: 0003 loss_train: 0.9843 acc_train: 0.9714 loss_val: 22.8118 acc_val: 0.0000 time: 0.0068s
Training complete in 0m 0s
Best val Acc: 0.000000
Epoch: 0004 loss_train: 1.2179 acc_train: 0.9714 loss_val: 26.0285 acc_val: 0.0000 time: 0.0057s
Training complete in 0m 0s
Best val Acc: 0.000000
Epoch: 0005 loss_train: 1.5536 acc_train: 0.9714 loss_val: 27.0566 acc_val: 0.0000 time: 0.0109s
Training complete in 0m 0s
Best val Acc: 0.000000
Epoch: 0006 loss_train: 1.0680 acc_train: 0.9714 loss_val: 26.9083 acc_val: 0.0000 time: 0.0052s
Training complete in 0m 0s
Best val Acc: 0.000000
Epoch: 0007 loss_train: 1.7013 acc_train: 0.9714 loss_val: 25.0974 acc_val: 0.0000 time: 0.0051s
Training complete in 

In [72]:
for name, param in model.named_parameters():
    print(name, param)

gc1.weight Parameter containing:
tensor([[ 0.1911,  0.2075, -0.0586,  ...,  0.0339,  0.1205, -0.0353],
        [ 0.1927,  0.0370, -0.1167,  ..., -0.2469,  0.2258, -0.2124],
        [ 0.1930,  0.0416, -0.0812,  ..., -0.1093,  0.1443,  0.0447],
        ...,
        [-0.1698, -0.0045, -0.1219,  ..., -0.0332, -0.1029, -0.2023],
        [-0.0655,  0.1893,  0.0871,  ...,  0.0358, -0.1784,  0.1259],
        [ 0.2226, -0.1175, -0.2049,  ...,  0.0851,  0.0107,  0.2146]],
       requires_grad=True)
gc1.bias Parameter containing:
tensor([ 0.2035,  0.0199,  0.2153,  0.0877,  0.0459, -0.0409, -0.0520, -0.0142,
         0.0124, -0.0377,  0.0293,  0.1532,  0.1146, -0.1783,  0.1550,  0.0816],
       requires_grad=True)
gc2.weight Parameter containing:
tensor([[ 0.0308, -0.3458],
        [-0.2816,  0.0041],
        [ 0.1889, -0.7018],
        [-0.2627,  0.1501],
        [ 0.3917, -0.3956],
        [-0.3303, -0.0182],
        [ 0.3845,  0.5243],
        [-0.6911,  0.6710],
        [ 0.0750, -0.6707],
  

In [101]:
#def test(model, adj, features, labels, idx_test):
model.eval()
output = model(features, adj)
print(output.shape)
print(output)
loss_test = F.nll_loss(output[idx_test[:354]], labels[idx_test[:354]])
acc_test = accuracy(output[idx_test[:354]], labels[idx_test[:354]])


print("Test set results:",
      "loss= {:.4f}".format(loss_test.item()),
      "accuracy= {:.4f}".format(acc_test.item()))

torch.Size([854, 2])
tensor([[-0.3693, -1.1751],
        [-0.3693, -1.1751],
        [-0.3693, -1.1751],
        ...,
        [-0.3693, -1.1751],
        [-0.3693, -1.1751],
        [-0.3693, -1.1751]], grad_fn=<LogSoftmaxBackward>)
Test set results: loss= 1.1010 accuracy= 0.1102


In [74]:
features.shape

torch.Size([854, 3501])

In [75]:
aab = input().split(',')

salt, egg, oil, rice, chile, onion


In [76]:
aab

['salt', ' egg', ' oil', ' rice', ' chile', ' onion']

In [77]:
features.shape

torch.Size([854, 3501])

In [78]:
all_ingss = list(pd.read_csv('/home/ashvinee/Documents/Ferrato/Data/all_ingredients_name.csv')['In'])
all_ingss

['salt',
 'pepper',
 'butter',
 'garlic',
 'sugar',
 'flour',
 'onion',
 'olive oil',
 'water',
 'ground',
 'olive',
 'powder',
 'sliced',
 'eggs',
 'black pepper',
 'milk',
 'cheese',
 'cream',
 'lemon',
 'chicken',
 'sauce',
 'tomatoes',
 'brown',
 'white',
 'egg',
 'onions',
 'vinegar',
 'vegetable',
 'brown sugar',
 'lemon juice',
 'ground black pepper',
 'parsley',
 'cinnamon',
 'garlic cloves',
 'extract',
 'vegetable oil',
 'vanilla',
 'baking powder',
 'vanilla extract',
 'unsalted butter',
 'ginger',
 'chocolate',
 'leaves',
 'soda',
 'parmesan',
 'tomato',
 'celery',
 'potatoes',
 'kosher salt',
 'mustard',
 'cheddar',
 'juice',
 'baking soda',
 'kosher',
 'sour cream',
 'cilantro',
 'soy sauce',
 'cream cheese',
 'parmesan cheese',
 'cheddar cheese',
 'oregano',
 'red pepper',
 'carrots',
 'clove',
 'chicken broth',
 'mushrooms',
 'honey',
 'packed',
 'orange',
 'bread',
 'thyme',
 'oil',
 'basil',
 'seasoning',
 'extra',
 'margarine',
 'mayonnaise',
 'bell pepper',
 'cayenn

In [79]:
ing_len = len(all_ingss)
new_arr = np.zeros(ing_len).astype(int)
new_arr

array([0, 0, 0, ..., 0, 0, 0])

In [80]:
ing_len

3500

In [81]:
for item in aab:
    ing_str = item.replace(" ", "")
    indx = all_ingss.index(ing_str)
    new_arr[indx] = 1

In [82]:
new_arr.shape

(3500,)

In [83]:
new_arr = np.array([0]+list(new_arr)).astype(int)
#new_arr = torch.from_numpy(new_arr)
new_arr.shape

(3501,)

In [85]:
feat = features[:853,:]
feat = feat.cpu().detach().numpy()
feat.shape

(853, 3501)

In [86]:
[[1,2],[3,4]]+[[5,6]]

[[1, 2], [3, 4], [5, 6]]

In [87]:
liss = []
for i in feat:
    liss.append([int(j) for j in list(i)])
    

In [92]:
featt = np.array([list(new_arr)]+liss)
new_featt = torch.from_numpy(featt)
new_featt.shape

torch.Size([854, 3501])

In [96]:
TFeat = sp.csr_matrix(new_featt, dtype=np.float32)

In [97]:
feats = torch.FloatTensor(np.array(TFeat.todense()))

In [98]:
model.eval()
output = model(feats, adj)

In [99]:
output

tensor([[-0.3693, -1.1751],
        [-0.3693, -1.1751],
        [-0.3693, -1.1751],
        ...,
        [-0.3693, -1.1751],
        [-0.3693, -1.1751],
        [-0.3693, -1.1751]], grad_fn=<LogSoftmaxBackward>)

In [100]:
output[0]

tensor([-0.3693, -1.1751], grad_fn=<SelectBackward>)